var dir_44bd96b7bce3b4c4b81443351cfe2b4f =
[
    [ "ParameterView", "dir_ab2e3457ff599272a5b2adbd13ca3815.html", "dir_ab2e3457ff599272a5b2adbd13ca3815" ],
    [ "about_section.cpp", "about__section_8cpp.html", null ],
    [ "about_section.h", "about__section_8h.html", "about__section_8h" ],
    [ "AudioChainSection.cpp", "_audio_chain_section_8cpp.html", null ],
    [ "AudioChainSection.h", "_audio_chain_section_8h.html", "_audio_chain_section_8h" ],
    [ "EffectList.cpp", "_effect_list_8cpp.html", null ],
    [ "EffectList.h", "_effect_list_8h.html", "_effect_list_8h" ],
    [ "EffectsModuleSection.cpp", "_effects_module_section_8cpp.html", null ],
    [ "EffectsModuleSection.h", "_effects_module_section_8h.html", "_effects_module_section_8h" ],
    [ "header_section.cpp", "header__section_8cpp.html", null ],
    [ "header_section.h", "header__section_8h.html", "header__section_8h" ],
    [ "main_section.cpp", "main__section_8cpp.html", null ],
    [ "main_section.h", "main__section_8h.html", "main__section_8h" ],
    [ "MasterEnvelopeSection.cpp", "_master_envelope_section_8cpp.html", null ],
    [ "MasterEnvelopeSection.h", "_master_envelope_section_8h.html", "_master_envelope_section_8h" ],
    [ "modulation_manager.cpp", "modulation__manager_8cpp.html", "modulation__manager_8cpp" ],
    [ "modulation_manager.h", "modulation__manager_8h.html", "modulation__manager_8h" ],
    [ "ModulationModuleSection.cpp", "_modulation_module_section_8cpp.html", null ],
    [ "ModulationModuleSection.h", "_modulation_module_section_8h.html", "_modulation_module_section_8h" ],
    [ "ModulationSection.cpp", "_modulation_section_8cpp.html", null ],
    [ "ModulationSection.h", "_modulation_section_8h.html", "_modulation_section_8h" ],
    [ "ModuleList.cpp", "_module_list_8cpp.html", null ],
    [ "ModuleList.h", "_module_list_8h.html", "_module_list_8h" ],
    [ "modules_interface.h", "modules__interface_8h.html", "modules__interface_8h" ],
    [ "ModuleSection.cpp", "_module_section_8cpp.html", null ],
    [ "ModuleSection.h", "_module_section_8h.html", "_module_section_8h" ],
    [ "SoundModuleSection.cpp", "_sound_module_section_8cpp.html", null ],
    [ "SoundModuleSection.h", "_sound_module_section_8h.html", "_sound_module_section_8h" ],
    [ "test_section.cpp", "test__section_8cpp.html", null ],
    [ "test_section.h", "test__section_8h.html", "test__section_8h" ]
];